### ISSUE TITLE
make examples using exposed FCVA Widget

### ISSUE THREAD

**Issue by ShootingStarDragon** [ShootingStarDragon/213d#261]
- [x] fix up specfiles
- [x] 2 examples, no console and console
- [x] there is a problem with mediapipe: dont have examples folder because I only check for the 1st one and the path gets wrekt
- [x] MORE ISSUES:
	- [x] noticed that seek was stuck again idk how to replicate... (it has smth to do with play/pause and seek causing things not to work right)
	- [x] multiple windows showed up during startup, what are they??? (created issue)
	- [x] when u load a new file the total time should also update (created issue)
	- [x] remove haarcascade example (leave it in)
	- [x] created issue
		- [x] mac: UPX not installed: https://stackoverflow.com/questions/70327138/163-info-upx-is-not-available-selenium-pyinstaller-one-file-exe
		- [x] upx not found also implies appsize is large (which is true...)
	- [x] mac unix executable works but not .app, (fixed, i refer to the correct filelocation now)
	- [x] https://pyinstaller.org/en/v3.3.1/usage.html#building-mac-os-x-app-bundles
	- [x] https://stackoverflow.com/questions/55592165/pyinstaller-executable-cant-run-on-other-machines-os-x
	- [x] compile all examples and run on:
		- [x] checklist:
			- [ ] pause/play
			- [ ] seek
			- [ ] EOS
			- [ ] drag and drop
			- [ ] works on its own folder
			- [ ] works on repeat plays
			- [ ] works in its own folder (esp on MAC)
		- [x] windows (cleared, now recompile with console = False)
			- [x] backsub
			- [x] cannyedge
			- [x] ~haarcascade~ literally too slow, mediapipe is better anyways, see: #302 
			- [x] mediapipe
			- [x] sepiafilter
		- [x] mac
			- [x] backsub
			- [x] cannyedge
			- [ ] haarcascade
			- [x] mediapipe
			- [x] sepiafilter
- [x]  you dont need to import mediapipe for the other examples... (leave it in but it's an easy fix) #294
- [x] as per #212, add the font file to pyinstaller spec file
- [x] HOPE THIS WORKS AS INTENDED FOR THE DROP IN WIDGET 
 ```
print("FCVA FCVAWidget __init__ detected no multiprocessing, importing as such", e, flush=True)
 ```
- [x] figure out how to give access to ppl < recieved from #199
	- [x] most likely I will need to make it a class and then expose it for ppl to import and use
		- [x] class will do the if name == fcva trick
		- [x] then import the required stuff
		- [x] HERE I should init the subprocesses... (when to exit tho???)
		- [x] then provide the kv code so u can just append it to ur kv
		- [x] what YOU neeed to do is just  use FCVAWidget: in ur kv
	- [x] MEANS:
		- [x] be able to change the kv string
		- [x] drop it in to kivy main subprocess'
	- [ ] tutorial everything
	- [ ] how it works
	- [ ] how to make ur own
	- [ ] how to make spec file 
	- [ ] etc

**Comment by ShootingStarDragon** [comment]
https://stackoverflow.com/questions/28349359/pyinstaller-single-file-executable-doesnt-run

**Comment by ShootingStarDragon** [comment]
https://stackoverflow.com/questions/68909011/cant-get-pyinstaller-to-work-with-onefile-and-noconsole
https://stackoverflow.com/questions/50463238/subprocess-seems-not-working-in-pyinstaller-exe-file/51706087#51706087
https://stackoverflow.com/a/57582101
https://stackoverflow.com/a/64955942

**Comment by ShootingStarDragon** [comment]
TRY ONEFILE AND SEE IF THAT WORKS
IF NOT BREAK DOWN THE APP UNTIL U FIND OUT WHATS THE ISSUE
ALSO TRY REBUILDING FIRST BEFORE DOING CRAZY STUFF
