### ISSUE TITLE
before posting, must know if it works from pypi

### ISSUE THREAD

**Issue by ShootingStarDragon** [ShootingStarDragon/213d#286]
- [x] as per #212, need to know if md ttf file is added
- [x] need to know if examples go along as well, etc
- [x] what is this on pypi?
	- [x] done ~ > added to todolist -what FCVA is about (sell) -fast -runs on opengl (kivy) -cross platform: tested with pyinstaller on windows and macOS (m1-silicon) ~images/examples Initial setup Running examples: Creating a simple example community; kivy discord documentation: readthedocs
- [x] UPDATE: i got it to work from root folder
- [x] i think the fix to get it to work: from root folder, from fastcvapp/fastcvapp AND fastcvapp/fastcvapp/examples is to just check your cwd and do a toggle like you do in example_mediapipe. just have to check for directory structure, so in the case of examples, check for `fastcvapp/fastcvapp/examples` and in the case of `fastcvapp/fastcvapp` also check for that structure, problem solved
- [x] just check from comparison of the #namespae branch to the main branch and add the checks there
- [x] also need to check if it works on mac, back to hell again since u have to check FOR BOTH WIN AND MAC, project (root, fastcvapp/fastcvapp, fastcvapp/fastcvapp/examples), AND ALSO ALL THE SPEC FILES AGAIN... 
- [x] rebuild pypi package > update version INCREMENTALLY on pypi then update my testfolder and check if I can just copy example_mediapipe.py
- [x] THERE ARE 4 LOCATIONS TO CHECK fastcvapp, fastcvapp/fastcvapp, fastcvapp/fastcvapp/examples and a legit outside source. Keep this in mind: It is the script's directory that is added to sys.path! 
- [x] https://stackoverflow.com/questions/6416424/why-does-my-python-not-add-current-working-directory-to-the-path
- [x] I know why it doesn't work, because I made the check to be more stringent:
- [x] old check
```
    if "examples" in os.getcwd().split(os.path.sep)[-1]:
        sys.path.append(
            ".."
        )  # when running from examples folder, append the upper level
    else:
        # assume they're in main folder trying `python examples/example_backgroundsubtraction.py`
        sys.path.append("../FastCVApp") 
```
- [x] new check
```
#     # if you're making your own app, you don't need this if-else block. This is just vanity code so this file can be run from main FastCVApp folder or from the examples subfolder.
#     # this example is importing from a higher level package if running from cmd: https://stackoverflow.com/a/41575089

#     # add the right path depending on if you're running from examples or from main folder:
#     # print("is file correct location?", __file__ )
#     print("check this out", os.path.join("fastcvapp", "fastcvapp", "examples").lower() in os.getcwd().lower(), os.path.join("fastcvapp", "fastcvapp", "examples"), os.getcwd())
#     print("checking these paths case insensitively: ",  os.path.join("fastcvapp", "fastcvapp", "examples").lower(), os.getcwd().lower())
#     #The windows file system is case-insensitive. https://stackoverflow.com/questions/21173979/how-do-i-get-path-to-python-script-with-proper-case
#     if os.path.join("fastcvapp", "fastcvapp", "examples").lower() in os.getcwd().lower():
#         sys.path.append(
#             ".."
#         )  # when running from examples folder, append the upper level
#         print("running from fcva examples folder!")
#     elif os.path.join("fastcvapp", "fastcvapp").lower() in os.getcwd().lower():
#         # assume they're in main folder trying `python examples/example_backgroundsubtraction.py`
#         sys.path.append("../FastCVApp")  # when running from main folder
#         print("running from fcva\ fcva  folder!")
```

- [x] check should be from fastcvapp (1) \fastcvapp (2) \ examples (3) (WINDOWS)
	- [x] fastcvapp (1) \
	- [x] fastcvapp (2) \ 
	- [x] examples (3) 
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc
	- [x] mediapipe
	- [x] rgb2rgba
	- [x] sepiafilter (confirmed slow aug 24 23 only on 1080p, it's fine on mac tho..) moved to later issue; https://github.com/AccelQuasarDragon/FastCVApp/issues/26
- [x] rebuild all the examples (WINDOWS)
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc (no specfile)
	- [x] mediapipe
	- [x] rgb2rgba (no specfile)
	- [x] sepiafilter (slow on 1080p windows, not confirmed but sure that 720p works)
- [x] check out all the specfiles
- [x] do the same for MAC : - )
- [x] check should be from fastcvapp (1) \fastcvapp (2) \ examples (3) (MAC)
	- [x] fastcvapp (1) \
	- [x] fastcvapp (2) \ 
	- [x] examples (3) 
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc 
	- [x] mediapipe
	- [x] rgb2rgba (smth is wrong with it, blit buffering wrong format)
		- [x] answer: 
		- [x] If this issue (https://github.com/AccelQuasarDragon/FastCVApp/issues/24) is not closed, to get this example to work you need to change 2 lines so you can blit RGBA and NOT! RGB which will cause errors
		- [x] this line so kivy will read an rgba frame properly
		- [x] frame = np.frombuffer(frame, np.uint8).copy().reshape(1080, 1920, 4)
		- [x] this line so that kivy blits rgba with Texture.create
		- [x] self.colorfmtval = "bgra"
		- [x] sepiafilter 
- [x] rebuild all the examples (MAC)
	- [x] backsub
	- [x] cannyedge
	- [x] haarcascade
	- [x] identityfunc (no specfile)
	- [x] mediapipe
	- [x] rgb2rgba (no specfile)
	- [x] sepiafilter
- [x] the examples work but for some reason the .app files DOUBLE their size after first run > yeah it's fine, when you show package contents you see that fcva did update correctly and used the correct root (sys.executable) which is similar behavior in WIN
- [x] check if examples work on a fresh comp (win/mac) if possible
- [x] check out all the specfiles
- [x] I think the problem is that ../fastcvapp is a relative import from getcwd?, i might have been lucky and from fcva/fcva folder ALWAYS got the fcva/fcva folder with ../fastcvapp relative import. If I just sys.path append the correct folder I will be fine OR change all my imports to be proper FastCVApp.FastCVApp. etc...
- [x] NEWER PLAN:
- [x] just add FastCVApp to path. from external source, add site-packages/FastCVApp. from github project, add /fastcvapp to path. SIMPLE SOLUTION TO COMPLEX PROBLEM SOLVED. This also means that packaging with pyinstaller should not be affected
- [x] PLAN:
	- [x] fix up mediapipe example on windows
	- [x] immediately go to mac and fix mac example
	- [x] then go back and check ALL use cases 🙃 
- [x] LMAO mac compiles so fast, new strat is to fix mac > go to windows
- [x] MORE PROBLEMS:
- [x] it's MAC filepaths vs windows filepaths. basically I need to get it right on both then figure out how to code it... the thing is the difference between cwd in windows and mac

different locations from python in WINDOWS and MAC

__file__ the actual damn file location, you can't go wrong with this

os.getcwd() 
on windows it depends on what cmd is. in a pyinstaller exe, it's the .exe folder NOT MEIPASS folder (that is sys._MEIPASS)
on mac since the meipass folder does not exist os.getcwd is just the app folder

so on mac sys.executable is where the actual exe is

acutally nvm, I was pointing to the actual file, not to examples folder... just more fatigue mistakes 🙃 

- [x] congratz, I just learned I was doing everything WRONG
- [x] example: I'm giving a relative path to update resources
- [x] I put the taskfiles in CREATIVECOMMONSMEDIA LOL
- [x] idk what else...
- [x] FIX: in update resources, specify the folder to copy and paste where, that way you are responsible. so sourcelocation = examples folder, dest = examples folder IN sys.executable
- [x] that seems reasonable...
- [x] remember: match getcwd on (mac/windows) (pyinstaller/vscode) and (source/dest)
- [x] also, just ask for full paths, but update folders with respect to `__file__` that's running it, like example_mediapipe.py 
- [x] no 1: YOU MUST DECIDE ON WHAT INFORMAATION TO PROVIDE
	- [x] this decision is actually determined by 2 things: running in code from fcva and fcva/fcva and fcva/examples. ALSO WHAT ABOUT FROM PYINSTALLER
	- [x] u need to pick the format and standardize, there is a huge difference between outside and inside the 2nd level fcva folder
	- [x] standardize two things: mediafile location and copying files over. I think the best way to do this is to assume you're from the outside, from topmost fcva folder 
	- [x] make reminder that destlocation is w.r.t. get cwd, which is the FastCVapp.py folder in code and FastCVApp.exe in pyinstaller
	- [x] reminder to typehint dest to be a list
- [x] no 2: FROM THERE MATCH EVERYTHING CORRECTLY
- [x] no 3: GET IT TO RUN FROM fastcvapp(1) fastcvapp/fastcvapp(2) fastcvapp/fastcvapp/examples (3) and also on pyinstaller
- [x] no 4: update all the examples
- [x] no 5: make sure they run on windows 🙃 
- [x] no 6: this is the time to remove the requirement to check for media on fastcvapp startup and widget btw ....
- [x] **THE SOLUTION AFTER LIKE 3 DAYS OF CRYING OVER IT:**
- [x] no 1: add the fastcvapp/fastcvapp.py folder using rglob on sys.path +[os.getcwd()] and os.path.getdirname
- [x] no 2: then in FastCVApp.py make the filesearching smarter by doing similar, looking for the file using rglob through sys.path+[os.getcwd()]
- [x] IT WORKS SEE BIGO/3 branch
- [x] so basically the solution was above ^
- [x] one last thing to fix is FCVA update resources though, I need to change it to be more generic (aka send examples folder to examples folder, not search for the creativecommonsmedia and copy that)
	- [x] testing if it works if i add a py file to update resources on win&mac
	- [x] py file worked on mac 
	- [x] py file worked on windows
