### ISSUE TITLE
checklist of things to check/make unittests on (sent to accel)

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/213d#315]
- [ ] reminder to future me:
- [ ] testing pyinstaller on macm1 is ok because compiling is fast
- [ ] for windows it is not fast, instead TEST ON A --onefolder INSTEAD!
- [ ] .
- [ ] check if all examples run on all cwds (from fastcvapp, fastcvapp/fastcvapp, fastcvapp/fastcvapp/examples) and on win/mac AND when made with pyinstaller AND when made with pyinstaller/upx as per https://github.com/ShootingStarDragon/213d/issues/286
- [ ] another thing is probably have the command in a py file just in case i forget:
- [ ] example: `python -m PyInstaller WIN_Mediapipe.spec --clean`
- [ ] also reminder that in order to make a smaller exe pyinstaller LITERALLY ADDS YOUR ENTIRE MODULES LIST FROM PIP so if you do a minimal env > do pyinstaller that is an ez way to make a small exe

sent to https://github.com/AccelQuasarDragon/FastCVApp/issues/22
