### ISSUE TITLE
NEW PLAN FOR A_DS

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/213d#322]
- [x] idea: that way a "full clear" is actually so that all the poses are gone since u did it perfectly
- [x] oct 31 23:
	- [x] solution 
	- [x] send these to shareddict
		- [x] show_future_pose_time
		- [x] show_analysis_time
		- [x] video_time
	- [x] copy this logic over to blit buffer in fcva
		- [x] show_future_pose_time = 1
		- [x] show_analysis_time = 1
		- [x] video_time = (time.time() - FCVAWidget_shared_metadata_dictVAR2	["starttime"])
		- [x] test_time = video_time % (show_future_pose_time + show_analysis_time)
		- [x] if test_time < show_future_pose_time and future_test_frame == None:
	- [x] if test_time < show_future_pose_time and future_test_frame == None:
		- [x] then do regular pose estimation (don't give the scoredict so 	draw_available_landmarks just draws on the future pose)
	- [x] else:
		- [x] do scoring of user pose
	- [x] update camera correctly now, alternate between showing future pose and displaying corrected score
		- [x] #ok, so it does the future graded frame, now to alternate datasets somehow...: look at show_future_pose_time, show_analysis_time
		- [x] tldr change open camera func then update the shareddicts so draw_available_landmarks flips between showing future and showing grading
	- [x] hint: transfer required functions (like draw halflines) using shareddicts and also then give data, only compose on blit buffer imo, and time it as well, print err message when blit takes more than 1/30th of a sec (transfer was complete and relatively painless since I setup all the systems for helper_func_dict)
- [x] oct 29 23:
	- [x] inner try block is messing with debugging on open camera subprocess (just turned on exception printing...)
	- [x] there are 2 bugs happening at once
		- [x] the 0 pose bug because I keep leaning out of the way of the camera (works for the moment, just set listangles to all be "outofbounds")
		- [ ] ~still trying to draw the correct pose on final image (aka need to respect lengths, maybe i have an x/y switched again)~
		- [x] tl:dr; fix draw_halflines, find out the correct point so as not to draw super long lines for no reason: 
		- [ ] ~ANSweR: MAKE SURE TRANSLATION IS ON THE CORRECT UNIT TYPE, PIXEL OR PERCENTAGE (percentage is completely different than per pixel, u need to account the different image dimensions between source image and camera)~
			- [ ] ~note: angle is ok, but it might be the pos of myself is legit outside~ 
		- [ ] ~try respecting a resize/the diff aspect ratios, then if not color and show user angle >yea, it's not the magic sauce, issue sent to~ #341
	- [x] time to blit buffer the final composited image
	- [x] modify dumpimages to include any amt of images side by side (so take images as a list)
	- [x] just need to normalize the scoring to the ans test, aka take the midpoint from the answer and then use the test angle
	- [x] braindead answer: ans pose of point 12 and testpose point 12> translate testpose of point 12 to ans pose of point 12 and apply that simple transposition to all points, this disrespects lengths tho
	- [x] split it to two funcs, just drawing landmarks, drawing test data on answer image, (nah don't split anymore)
	- [x] remember that this is a final image so have camera update that to shared dict, keep original posedata as a display as well 
	- [x] Future pose will be 1 color (gold for lines, red for pose dots)
	- [x] graded pose will be color coded(????,????)
	- [x] Pay a ux designer after it's done
- [x] oct 28 23:
	- [x] there is a legit error when u cannot find a pose (temp solved)
	- [x] return typoe? <class 'numpy.ndarray'> 0
	- [x] the drawing code for draw_available_landmarksrpc TAKES TOO LONG
- [x] oct 25 23:
	- [x] write out pictures to folder.... (hard to see in real time to manually make score)
		- [x] VDS 2.0: 
			- [x] dumpImages
	- [x] pose is delayed wtf
		- [x] code of fcva is even the same
		- [x] tried on a naked env, I think it's confirmed that fcva loaded as a module is just inherently slow...
		- [x] NOPE, IT'S THE MEDIAPIPE VERSION 10.7 SUCKS 10.3 IS THE WAY TO GO
	- [x] PLAN:
		- [x] draw and dump in debugads folder
		- [x] make sure scores are correct/they exist in the first place
			- [x] checked score according to 'manually' doing calculations.py, lgtm
		- [ ] ~overlay the "pose subtraction" that you did wrong (reference #323)~ > sent to #341 
			- [ ] ~3 parts to this~
				- [x] create a function to draw the stuff that is: not oob, what I want (which will switch from all to the ones that you failed)
					- [x] Colors (for lines and circles)
					- [x] Green or red(fail) maybe orange since red is good in china?
					- [x] look at a color wheel, maybe green is "bad"? maybe try purple					
					- [x] try this green: rgb(102, 255, 102) (since we're sensitive to green apparently)
					- [x] in cv func i can check if camera has chosen the future pose then draw that pose in so i don't have to mess with fcva.py
					- [x] Really think about it: 
					- [x] ur always drawing pose (that is the default state)
					- [x] success should be: removal of pose
				- [x] move pose drawing code to blit buffer (draw what's on some updated shared dict)
					- [ ] ~need option to flip pose (what is correct pose? it should be for an audience not for self so u gotta flip on the vertical axis (swap L/R))~ > sent to #343
				- [x] u need to go in cycle: 1 sec show future, 1 sec show scoring, or look at how other rhythm games do it
				- [x] android notes
					- [x] So in blit probably just draw the cv stuff
					- [x] Make a func called: draw pose from coords
					- [x] Then have a latest shareddict where coords are added/removed based on performance
					- [x] Ao there are 2 undrawn states: oob and HIGH score (use a change to show success)
	- [x] helper func: draw data on cam based on posedata (look at ADS2), have it already it's called visualGradeCheck and draw_landmarks_on_image
- [x] plan oct 18 2023:
	- [x] isn't this bad? I should not have dance star specific code online
	- [x] just go make the thing and reference stuff in A_DS now I guess
	- [x] like for example, put open_camerapipeline in VDS, also ??? ?? ??
	- [x] cheat way to be just to make amazingdancestar.py and add to gitignore or smth, or 	even better go to ADS repo right now and just make a wheel with poetry to load
	- [x] new to do:
		- [x] **make it so fcva can reference helper funcs from ads**
			- [x] 1 need to import openmediapipe helper from fcva
			- [x] 2 get fprint
			- [x] 3 get draw_landmarks_on_image
			- [x] get all the other imports
			- [x] 4 make it so that fcva uses func supplied in example_mediapipe2
			- [x] How do i access code from ads.py and not get circular logic'd?
			- [x] ~Just have a list of funcs and do smth like app.helperfuncs = [list of functions]~ > nah, do a dictionary so u can still see the name, refresher (use parens to call the func and apply args) https://www.geeksforgeeks.org/python-store-function-as-dictionary-value/#
				- [x] ~Then in code do smth like self.helperfuncs[0] or smth~ dict is easier for the eyes
		- [x] go from fcva to ads
			- [x] use custom wheel 
			- [x] check out examplemediapipe2.py
		- [x] get drawing code (draw purple, with green circles etc)
			- [x] RPCdir
			- [x] FOUND IT: visualGradeCheck
		- [x] Draw angles
			- [x] get angle code working
			- [x] look at at pose dir.png in vdspythonpivot
			- [x] make sure they all show
		- [x] get compare code (analyzeDualDicts)
			- [x] analyzedualdicts is actually very short, just check it out. I think args 0, 1 are just shareddicts (so irrelevant to ads 3.0). also all it does is check dictionaries, probably arg2 is useless as well
			- [x] figure out how to get the "out of bounds" check:
				- [x] preDict[str(anglechoice)] = "outofbounds" (it's built into analyze dualdicts)
			- [x] actually analyzeframeindex is the FRAME NUMBER (aka irrelevant), YO WE ARE GONNA REMAKE IT EASILY
	- [x] plan oct 15 23 (12:20AM):
- [x] there are 2 chains:
	- [x] make a map of these and stick it in ads folder
	- [x] chain1: ADS repos
		- [x] G>TBO, TBO FDRIVE
	- [x] chain2: FCVA -> ADS
		- [x] TL:DR; i need to update fcva before updating ads (nah, just make local whl with poetry)
			- [x] no1: figure out what updates I need
			- [x] quickly update fcva
			- [x] work on it on ads
		- [x] how to make sure they 
	- [x] probably move to separate A_DS repo now,
	- [x] https://stackoverflow.com/a/44441041
	- [x] braindead answer:
		- [x] local area share folder
		- [x] git clone the shared folder
		- [x] ggs
	- [x] get the compare code from old A_DS
		- [x] newer plan:
			- [x] stop copying the old stuff
			- [x] see if old drawing func works (good indicator that format did not change)
				- [x] can't find it atm, just keep going
				- [x] code between versions is similar, pretty sure I can port it (I did, )
					- [x] old: results.pose_landmarks.landmark[12].x
					- [x] new: cam_pose_results.pose_landmarks[0][14].x
			- [x] well RIP, posedata is not in a shareddict, i can probs be lazy and just do it AGAIN in camerapipeline, but need to make an issue for it
				- [x] ~don't do it again, just be even lazier and attach it to the key shareddict, anyways I don't think that is counted (I hope)~
				- [x] nope, really make a new shareddict for it, don't cheat (nah, I added it already, found it)
				- [x] shared_posedict_list is vague, have to rename to say SOURCE or CAM, I already have shared_camerapose_list,
				- [x] figure out how to get right dict in shared_posedict_listVAR2 in open_camerapipeline
				- [x] it's literally the same format as sharedanalyzed and shared analyzed keycount... 
				- [x] realer problem... need to instantiate another mediapipe instance because I need to create a posegraph from image... that's giga cringe
				- [x] make the landmarker code into another callable function JK, then in cvfunc and camerapipeline do: landmarker = JK() and if there's more vars do: landmarker, var1, var2 = JK() and jk returns them as a list
			- [x] i have posedata from source, cam
		- [x] oct 25 23: I GOT SUPER LUCKY THE OLD CODE WORKED WITH SOME FIXES
			- [x] filter out posedata to get the angles I want
			- [x] compare 2 poses
			- [x] create score
			- [x] ~overlay the "pose subtraction" that you did wrong~ > sent to top
			- [x] ~helper func: draw data on cam based on posedata (look at ADS2)~ > sent to top
		- [x] plan:
			- [x] look at how ADS 2 does it
			- [x] get pose estimations for the 2 frames
			- [x] filter out for what angles I'm looking for 
			- [x] as per vds ui, look at:
				- [x] analyzeDualDicts
				- [x] RPC_LetterScore
				- [x] gradingCurve
				- [x] RPCmagdiffhelper
				- [x] RPCmagdiff
			- [x] understand this chain in ads 2:
				- [x] analyzeDualDicts
				- [x] analyzeDualDicts([linkSharedDict,camSharedDict,undoneframe]) 
				- [x] camSharedDict in RPC_megaprocess 
				- [x] mediascananddisplay(camFrame,"CAM", camframenumber, camSharedDict, camSharedDictImage,camAnalysisSharedDict) 
				- [x] mediascananddisplay
			- [x] remember for test mode u can just cheat it out and print the screen using .pixels on window... or just use stitching from vds 2.0
- [x] plan oct 10 23:
	- [x] change screen to show more textures (search: FCVAWidget>:)
	- [x] steps:
		- [x] show 4 images:
		- [x] current image (current pose)
		- [x] future image (future pose) (future_textureID)
		- [x] camera image (current camera pose) (camera_textureID)
		- [x] pose subtracted image (final_imageID)
- [x] newer todo oct 1 23:
	- [x] add posedata and check if it's updated correctly
		- [x] test this by adding the current pose to a clean (no pose) frame
	- [x] figure out how to run the new subprocess, and where
		- [x] Insert compare subprocess when cvsubprocess is opened (add to bottom of FCVAWidget_SubprocessInit) (make sure subprocess and actual posedata are matched properly)
		- [x] subprocessVAR.kill() on on_request_close for the camera subprocess
		- [ ] ~remember to reset interval on seek~ > #334
		- [x] write the camera subprocess func
		- [x] return correctly in FCVAWidget_SubprocessInit
		- [x] ~add to __init__ of FCVAWidget under initdatalist so I get access to it using self (not necessary anymore imo)~
		- [x] problems:
			- [x] no1: if the xyz format is still the same (it should be)
			- [x] no2: how to see the drawn images again
	- [x] Now it's time to create the generic of the cycle: run when video is running, compare 2 poses, create score, ggs I win
		- [x] compare 2 poses 
	- [x] remember to separate out mediapipe example and fcva
- [x] NEW TODO sept 27 23:
	- [x] clean up print on blit buffer
	- [x] **get the pose data added as well** 
		- [x] ~TL:Dr; match the system i already had with framedata~
			- [x] ~YOU NEED TO MATCH THE SYSTEM BECAUSE THERE ARE BATCHES OF FRAMES AT DIFFERENT STAGES, START FROM appliedcv THEN GO TO UPDATE SHAREDDICTS, AND REMEMBER TO CLEAR WHEN UPDATING FROM SEEK~ > sent to #338
		- [ ] ~make sure posedata is updated properly~
			- [ ] ~on seek~ >#334
	- [x] make a new subprocess to compare data
- [x] #NOTE: appliedcv_init IS NOT A TIMER HISTORY OF A FRAMEBLOCK! THIS IS JUST TIMER INFO OF THE TIMINGS OF THE CURRENT BATCH OF FRAMES!
- [x] TODO
	- [x] future time is DEF wrong, need to calculate on a PER BLOCK basis IMO, futuretime(FIRST FRAME OF ANALYZED BLOCK) - time.time()
	- [x] get time to match by peeking on the key deque
- [x] if I have access to the metadict I can just modify the cv func in ADS (not really: IN FCVA) (didn't end up doing this)
	- [x] insert pose, timer dict into metadict (didn't end up doing this)
		- [x] add time taken @ each stage then when fcva shows that's when u print
	- [x] create timerdict of all the breakpoints
		- [x] insert timedict to metadict somehow, that is "revolving" so the dict doesn't bloat in size
		- [x] look at how the framecount is made
		- [x] PROBLEM: insert everything correctly, already made dicts and added to open_cvpipeline. I just need to INSERT PROPERLY, need to go through flow again and THEN update dicts
		- [x] will also have to update fcva
- [x] IN ADS
	- [x] compare 2 poses
		- [x] 1 more subprocess
		- [x] get pose data from shared dict @ right time
		- [x] get pose data from camera (hint: not per-frame operation so this is ok)
		- [x] compare (get code from ADS V2)
		- [x] show on UI
	- [x] don't have to display drawn pose since u need to show FUTURE pose 
	- [x] get audio somehow, ffpyplayer subprocess? (since thread might be slow)
		- [ ] ~check ffpyplayer on mac?~ #207
- [x] sept 25 23
- [x] make a new deque for the 2 datatypes:
- [x] timer
- [x] pose
- [x] since pose is towards the end it's kinda whatever
- [x] but for timerpose u gotta go from the beginning
- [x] 1 update shareddicts
	- [x] update data from deque
- [x] 2 applycv
	- [x] give data from deque
- [x] 3 update info if using seeking
	- [x] clear all the deques
- [x] 4 read frameblock many frames
	- [x] init dequescuriously there are 4 blocks now   
- [x] plan: 
	- [x] from collections import deque
	- [x] timerdeque = 
	- [x] timerdequekeys = 
	- [x] posedeque = 
	- [x] posedequekeys = 
- [x] what am i expecting?
- [x] do timerdata first:
- [x] timerdata is gonna hold a dict of the several steps that happened
	- [x] no1: what steps are important? <--- DO AT HOUSE 
	- [x] no A: time it takes to read (block 4)
	- [x] no B: time it takes to update data/clear deques (block 3) (may or may not happen)
	- [x] no C: time it takes to do code (resultdeque) + compress(blosc)
	- [x] no D: time it takes to update previous dicts (shared_analyzedVAR['frame'+str(x)]...)
- [x] do posedata second: 
- [x] get posedatas from cv func and stuff into shareddict through deque
- [x] how to quickly print keyvalue pairs from dict python 
- [x] just need to pass results somewhere, probably need to add the posedict to the cvfunc (results = landmarkerVAR.detect_for_video)
- [x] REMEMBER TO PRINT WHEN BLIT BUFFERING!
- [x] ok, let's imagine it:... just clear the errors one by one tbh, that's how i always do things
- [x] ok, just stall for time so i don't get psychological damage I guess, im pretty much done 11:12am
- [x] future steps: 
- [ ] ~need audio (ffpyplayer... could try out python-vlc maybe? run w/o window, only play audio)~ >#207
- [x] need to compare poses:
	- [x] make 1 more subprocess in the main.py where u have app. blah blah blah
	- [x] then that subprocess will read the current cameraframe
	- [x] compare two poses from the shareddicts (need to access fcva subprocess somehow)
	- [x] then i'll be done
- [x] maybe later I can do ffpyplayer again but for right now skip
- [ ] I still need to figure out how warframe is a free game and is able to sell plat, how does steam get a cut?
- [ ] ~then get old functionalities, > make steam page~ > #342
- [x] have early access that basically gives u it if u click to sign up
- [x] https://stackoverflow.com/a/44441041
If you're asking about how to connect to a repository hosted by another computer on the same network, take a look at [this StackOverflow thread](https://stackoverflow.com/questions/21273826/creating-a-remote-server-on-a-lan-instead-of-using-git-hub).
- [x] Basically, you'll want to use [git daemon](https://git-scm.com/book/en/v2/Git-on-the-Server-Git-Daemon). If you just need to set up a single repository, that's one line from each machine:
- [x] Server:
- [x] git daemon --base-path=/path/to/repo --export-all
- [x] Client:
- [x] git remote add LocalServerName git://<serveraddress>/
- [x] or
- [x] git clone git://<serveraddress>/
- [x] where <serveraddress> is some reference to that machine (IPv4, IPv6, .local, etc.). You can also specify --verbose for the daemon command for more detailed output.
- [x] I think, also, you could have --base-path point to a folder with many repositories, and that would let you specify which project you wanted on the client-side like so:
- [x] git daemon --base-path=/path/to/all/repos
- [x] git remote add ServerName git://<serveraddress>/MyProject/
- [x] Be advised: using --export-all will let any computer on the network pull from your repo.
- [x] https://medium.com/@clergeg/intro-to-git-daemon-using-your-local-environment-as-a-git-server-6d926f159f2c
