### ISSUE TITLE
package vlc somehow... (1st package to mac+ VLC problems listed here btw, dpi reference, screen module ref)

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/213d#356]
- [x] ADD LIBVLC TO MAC SPECFILE > PYINSTALLER VLC WORKS WHEN VLC IS INSTALLED ON SYSTEM EVEN THO U DIDNT ADD LIBVLC (libvlccore.dylib) > #398,  add-vlc-to-pyinstaller on kivyschoo
	- [x] u gotta fix vlc.py, u can even monkeypatch it, just reference add-vlc-to-pyinstaller on kivyschool >#398
- [x] ~sort this and fix > then remake in a new env > upload to itch and start prepping everything else >this is just pyinstaller exe pipeline,~ see #397 
- [x] **importing vlc w/o adding vlc to specfile at the top of fastcvapp.py BUGGED OUT pyinstaller and got it to crash silently (no complaining that vlc did not exist). that one line, WOW I SPENT 3 DAYS ON THIS** > couldn't reproduce error, hurray having a gigantic codebase
- [x] todo:
	- [x] sort this
	- [x] make note on the pull request about dpupdate (workaround that works on mac m1 w/ retina, asus vg???, screen module also works on s3 note2 droid2 checked on both monitors)
	- [x] respond to the guy on stackexchange about where is python vlc plugins
	- [x] make post on kivy blog about mac m1 has bad size
		- [x] https://github.com/kivy/kivy/pull/6289#issuecomment-1854403395
	- [x] [another post on kivy school: adding vlc to pyinstaller on MAC and WINDOWS](https://github.com/ShootingStarDragon/213d/issues/392)
	- [x] make vlc example and show it bugs tf out on pyinstaller if it's not collected by spec but still imported (no crash err reporting)
- [x] make note on the pull request about dpupdate (workaround that works on mac m1 w/ retina, asus vg???, screen module also works on s3 note2 droid2 checked on both monitors)
	- [x] (respond to this and add to reference) font issue: https://github.com/kivy/kivy/pull/6289#pullrequestreview-235299844
	- [x] originally the idea was high dp > draw smaller, low dp > draw bigger, but instead i think i got lucky and actually the density should be 1 regardless, and that sdl2 (or some other underlying code) is already adjusting for the retina display
	- [x] suspicion is that sdl2 or some other backend is already adjusting for retina display, so kivy doesn't have to
	- [ ] ~make a post about root.dpupdate on kivy on and get some more data points if it works or not~ -> sent to #400
	- [ ] ~post also includes links:~
		- [ ] ~how to calculate dp (2 websites)~
		- [ ] ~quick dive into kivy metrics~
		- [ ] ~how to use screen module~
		- [ ] ~how to check for os~
		- [ ] ~dpupdate fix~
- [x] make vlc example and show it bugs tf out on pyinstaller if it's not collected by spec but still imported (no crash err reporting)
	- [x] couldn't reproduce error, i think it's using system vlc but not willing to take out vlc from path
	- [x] make sure to unhardcode mediafile
	- [x] make sure to show the error, 2 exes (test where it does not crash silently, test 2 where it does crash silently)
	- [x] *just for completeness:* also write about how to add vlc to pyinstaller 
- [x] also write to chains and flows.graphml how I use shared network to git update everything/where the branches are/etc > cleared #391 
	- [x] make git issue about getting ads to mac/mac notes issue in documentation of projects > #393
	- [x] https://www.makeuseof.com/tag/how-to-easily-share-files-across-mac-windows-computers/
	- [x] used this to smb share from gaim (win 10) > rr nest (mac)
	- [x] https://www.themakersphere.com/setup-smb-file-share-on-windows/
	- [x] I could have shared originally with filesharing WTF? why did i use a usb to transfer? I guess getting vlc to work was more important, this step is good since that means i'm updating git frequently
	- [x] https://stackoverflow.com/questions/32495503/clone-git-repo-hosted-on-a-windows-shared-folder-from-mac-os-x
- [x] add vlc on mac...
	- [x] HINT
	- [x] https://github.com/pyinstaller/pyinstaller/issues/3448
	- [x] https://github.com/pyinstaller/pyinstaller/issues/3448#issuecomment-607933332
	- [x] sending to mac >
		- [x] have USB as "W:" drive
		- [x] git clone from ads MAIN folder
		- [x] then on mac git clone from USB 
	- [x] MAC NOTES:
		- [x] had to copy over latest fcva from fcvaCLONE 
		- [x] in fcva .venv (that is NOT tracked by git btw), renamed fastcvapp/examples/creativecommonsmedia > fastcvapp/examples/bin
		- [x] ICON IS SUPER BLURRY
		- [x] TEXT IS GIGANTIC/NOT SIZED RIGHT
			- [x] mac has no dpi in this block https://github.com/kivy/kivy/blob/master/kivy/metrics.py#L188
			- [x] (not the correct line but i think it's the right file)
			- [x] https://stackoverflow.com/a/1281659
			- [x] how to get screen dpi?
			- [x] HARDCODE IT FIRST TO SEE IF DP GETS FIXED THEN MAKE PR SOMEHOW
			- [x] https://github.com/rr-/screeninfo/issues/84
			- [x] https://stackoverflow.com/questions/57059128/ui-scaling-in-kivy-on-macos-with-retina-display
			- [x] ok i think since metrics is being read in kv u gotta set kivy dpi CORRECTLY AND EARLY somehow
- [ ] REFERENCE=-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-=
- [ ] dpi ~ ppi on this website
	- [ ] https://www.sven.de/dpi/
	- [ ] https://www.displayspecifications.com/en/model-display/8feaf0e
- [ ] density calc:
- [ ] https://github.com/kivy/kivy/blob/master/kivy/metrics.py#L250C12-L250C12
- [ ] :attr:`density` is a :class:`~kivy.properties.AliasProperty` and can be
    set to change the value. But, the :attr:`density` is reloaded and reset if
    we got it from the Window and the Window ``density`` changed. https://github.com/kivy/kivy/blob/master/kivy/metrics.py#L250C12-L250C12
- [ ] https://github.com/kivy/kivy/blob/master/kivy/_metrics.pyx
	- [ ] on windows it's correct at 96 dpi, dp(1 , 2) > 1.0,2.0
	- [ ] on mac ppi should be 227 but kivy says 192, dp(1, 2) > 2.0, 4.0
	- [ ]  now to find the correct calculation as per https://www.sven.de/dpi/ with these settings:
	- [ ]  2560x1600, diag: 13.3 inches > 226.98 PPI
- [ ] YOU CAN SCREEN EMULATE ON LPYTHON (screen module in kivy actually not native python)? https://github.com/kivy/kivy/issues/6144#issuecomment-490442172
	- [ ] https://www.reddit.com/r/kivy/comments/sy3cqb/how_do_i_emulate_on_my_pc_what_my_app_will_look/
	- [ ] https://github.com/kivy/kivy/blob/master/kivy/modules/screen.py
- [ ] Graphics/Displays category will tell you your screen resolution. 
	- [ ] https://superuser.com/a/131513
- [ ] dpi correct for windows, incorrect for mac retina display, thinking emoji might have to add a pr or smth
- [ ] https://github.com/kivy/kivy/issues/6144 > resizing window messes things > i checked and kivy works normally, even the fonts so it's closed correctly
- [ ] adding vlc to pyinstaller:
	- [ ] https://stackoverflow.com/questions/48336981/how-can-i-convince-pyinstaller-via-my-spec-file-to-include-libvlc-dll-in-the-e
- [ ] REFERENCEEND=-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-=
- [x] answer (what I did):
	- [x] dp is font*(1/kivy.metrics.Metrics.density)
	- [x] high density means u gotta get a smaller number
	- [x] low density means u gotta give a bigger number
	- [x] Not sure if this is a correct workaround as it works on my mac m1 but I cannot manually test on other screens> i tried with kivy.modules.screen with settings:  screen:one, screen:onex and screen: note2, it looked fine (on the mac)
- [x] answer (workaround):
	- [x] u have a fixed fucked up dp in kivy metrics
	- [x] it should only be a scale factor Y to fix to the "correct" dp 
	- [x] so fontsize should actually be smth like: font_size = root.Y*dp(value)*scale
	- [x] then u calculate Y based on os:
	- [x] if win, Y is 1
	- [x] if mac, Y is the magical value
	- [x] magical value (u know kivy metrics dpi is fixed, so go from fucked fixed value to a correct value scale)
	- [x] dpi calculation from kivy._value
```
cpdef float dpi2px(value, str ext) except *:
    """Converts the value according to the ext."""
    # 1in = 2.54cm = 25.4mm = 72pt = 12pc
    if g_dpi == -1:
        dispatch_pixel_scale()

    # all of these must linearly scale the value (10xx = 10 * 1xx)
    cdef float rv = <float>float(value)
    if ext == 'in':
        return rv * g_dpi
    elif ext == 'px':
        return rv
    elif ext == 'dp':
        return rv * g_density (just the monitor density i think) https://github.com/kivy/kivy/blob/master/kivy/_metrics.pyx#L36C18-L36C18
    elif ext == 'sp':
        return rv * g_density * g_fontscale
    elif ext == 'pt':
        return rv * g_dpi / <float>72.
    elif ext == 'cm':
        return rv * g_dpi / <float>2.54
    elif ext == 'mm':
        return rv * g_dpi / <float>25.4
```
- [x] do screen tests on mac `python amazingdancestar.py -m screen:s3` (they worked)
- [x] make issue for kivy school, sometimes u need to update kivy AND pyinstaller. spent 8 hours figuring it out... (pyinstaller was not the issue)
- [x]  write on kivyschool website I guess? idk
- [x] fix update resources to update "bin" that has all the stuff
	- [x] 1: send bin folder through with specfile
	- [x] 2: fcvaupdateresources on bin folder
	- [x] it just silently crashes, checking at fcvawidget subprocessinit
	- [x] taskfiles for mediapipe are not being pushed over, push them over from fcva to meipass folder
	- [x] get a diff of sys.modules
	- [x] next try: just don't builder load string see where it goes
	- [x] other try: build the other fcva example (can do it, copy example, copy specfile> build)
	- [x] might be multiple fcva module copies in pyinstaller
	- [x] turn off all subprocesses, get the button to work
	- [x] Just turn off everything
	- [x] turn off kivy subprocess and make basic kivy app instead, suspicion is kivy and deps are not being bundled by pyinstaller OR in wrong env somehow (wrong pyproj toml??? unsure)
	- [x] 2 things: taskfile, vlc
		- [x] another possible problem: pyinstaller works on fcva but won't work on ads because ads is running from wrong fcva or smth (some sort of env problem?)
		- [x] turned off vlc: YOU FORGOT TO STOP IMPORTING DUMBASS
			- [x] self.vlc_player = vlc.MediaPlayer
			- [x] self.vlcschedule = Clock.schedule_once(self.vlc_start, self.FCVAWidget_shared_metadata_dict['bufferwaitVAR2'])
		- [x] commented out self.FCVAWidget_KV = FCVA.FCVAWidgetInit(
		- [x] turn off icon and title
			- [x] # self.icon = ico_location
			- [x] # self.title = self.kvinit_dictVAR["title"]
		- [x] turn off inspector
```python
			 from kivy.modules import inspector
                         button = Button(text="Test")
                         inspector.create_inspector(Window, button)
```
- [x] .		
	- [x] ,
		- [x] UNDO BIN CHANGE Get  abd resources fplders again just  get it wprking -> undone
		- [x] there is also this discrepancy (fastcvapp in the env but no fastcvapp in tmp dir of pyinstaller)
```python
\_MEI191442\fastcvapp\fastcvapp.pyc 
\_MEI191442\fcvautils.py
```
- [x] .
	- [x] .
		- [x]  IT DID GET COLLECTED: 1900 1701391635.8115525 does fcva utils work in pyinstaller env??? AppData\Local\Temp\_MEI174002\fastcvapp\fcvautils.pyc
```python
import fastcvapp.fcvautils
fprint("does fcva utils work in pyinstaller env???", fastcvapp.fcvautils.__file__)
```
- [x] .
	- [x] .
		- [x] turned off openkivy even: target=self.open_kivy,
		- [x] at branch main in this sha1 `789f0589d8e7` I got "unable to provide window provider..." solution here:
		- [x] https://stackoverflow.com/questions/44219563/kivy-not-working-error-unable-to-find-any-valuable-window-provider
		- [x] added kivy.deps to hiddenimports as deperation move
		- [x] actually try making mediapipe fcva example legit (i already have example mediapipe, just need to copy over the spec file)
			- [x] run example mediapipe
			- [x] works
			- [x] make with pyinstaller and run
			- [x] renamed fcva bin folder in venv BACK to creativecommonsmedia... > undone
		- [x] I MIGHT BE USING THE WRONG VENV THE ENTIRE TIME???
		- [x] poetry show -v
		- [x] \vdspoetry2023\.venv
		- [x] insane the kivylogs still work, I can see what the error is!
		- [x] Here is the location of the kivy log files: C:\Users\YourUserNane\.kivy\logs
		- [x] https://groups.google.com/g/kivy-users/c/sVt_4_G7hnk/m/SLYLWmDbAwAJ
		- [x] https://stackoverflow.com/questions/49806573/cant-pyinstall-a-kivy-python-program
		- [x] try to add kivy deps as hiddenimports?
		- [x] DLL load failed while importing _window_sdl2:
		- [x] https://stackoverflow.com/questions/49482753/sdl2-importerror-dll-load-failed-the-specified-module-could-not-be-found-and
		- [x] kivy = "^2.2.1"
		- [x] kivy-deps-sdl2 = "^0.6.0"
		- [x] kivy-deps-glew = "^0.3.1"
		- [x] kivy-deps-gstreamer = "^0.3.3"
		- [x] basic app confirmed working, it's smth with fastcvapp and ads interaction...
		- [x] I was using latest kivy 2.2.1 and very old pyinstaller 5.11, let's see it... <--- THIS WAS THE PROBLEM, WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOW
		- [x] unable to get window provider as per logs (still), aka import again or smth?
		- [x] if it works on top level but not in subprocess u gotta add sys meipass to path IN THE SUBPROCESS
		- [x] upgrade python? no way...
		- [x] maybe kivy_deps as a hiddenimport REALLY IS the answer as well....
		- [x] it only works on the VERY topmost level... on ADS.py
		- [x] if i get kivy to work on try except block in ads.py i might be able to get it to work in fcva.py
		- [x] made initial try except block > kivy runs > now everything runs, so yet again it's some import error
		- [x] congrats, somehow the path append I do to make fcva work in ads.py is borking kivy
		- [x] so how to fix? 
		- [x] figure out what path appending im doing
		- [x] ???
		- [x] then why did fcva as a module work???
		- [x] another thing im doing was making a personal fcva instead of installing from pypi but that shouldn't matter right?
		- [x] anyways the first screen could be like a splash screen? idk
		- [x] now: REALLY try to use fcva as a module (in new venv) > make pyinstaller > see if it works/worked
		- [x] probably is fcva namespace collision (one in memory and one in tmpdir)
		- [x] SOMEHOW I FINALLY FOUND THE STUPID ERROR
		- [x] File 'C:\\Users\\d1\\AppData\\Local\\Temp\\_MEI54442\\fonts\\materialdesignicons-webfont.ttf' not found
full exception Traceback (most recent call last):
  File "fastcvapp\fastcvapp.py", line 1986, in open_kivy
  File "fastcvapp\fastcvapp.py", line 1964, in run
  File "kivy\base.py", line 574, in runTouchApp
  File "kivy\base.py", line 339, in mainloop
  File "kivy\base.py", line 379, in idle
  File "kivy\clock.py", line 733, in tick
  File "kivy\clock.py", line 776, in post_idle
  File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "kivy\uix\label.py", line 431, in texture_update
  File "kivy\core\text\__init__.py", line 820, in refresh
  File "kivy\core\text\__init__.py", line 406, in resolve_font_name
OSError: Label: File 'C:\\Users\\e1\\AppData\\Local\\Temp\\_MEI54442\\fonts\\materialdesignicons-webfont.ttf' not found
		- [x] idk why it wasn't showing before
		- [x] other issue: taskfile was still looking in examples/bin instead of just bin in tmpdir
		- [x] check multiprocessing freeze support first
		- [x] camera cannot find file? why not?
		- [x] the issue: you just imported fcva class NOT fcva module so the other imports just did not happen
		- [x] nope, import fcva happened in ads.py
		- [x] turned off the font because "can't find" errors
		- [x] # self.updatefont()
```python
# self.font_path = os.path.join(this_dir, "fonts", "materialdesignicons-webfont.ttf")
                        # fprint("what is fontpath??", self.font_path)
                        # Clock.schedule_once(self.updateRepeatButtonID, 0)
                        # Clock.schedule_once(self.updatevolumeLabelID, 0)
```
- [x] .
	- [x] ,
		- [x]  "SO EVERY SUB IS MAIN??? WHAT THE FUCK?"
		- [x] YEAAA SO ITS BREAKING BECAUSE KIVY IS TRYING TO RUN ALL THE TIME, WHY MAN
		- [x] THE PROBLEM IS IF NAME IS MAIN IS ALWAYS ACTIVE, SO EVERY SUBPROCESS TRIES TO RUN KIVY, NO BUENO
		- [x] WHAT DO? JUST HAVE A FLAG?
		- [x] 2: 
		- [x] opt 1
		- [x] opt 2 
		- [x] >installation
		- [x] turned off all the fonts
		- [x] with pillow AND import it worked, try w/o pillow
		- [x] Pillow = "9.5.0"
		- [x] > matplotlib needs it... ok
		- [x] do you get to got here5/got here4?
		- [x] it might be smth to do with having 2 copies and importing fcva.py from tmp folder modules and fcvautils.py from tmp folder base dir?
		- [x] could also remove fcva from hiddenimports
		- [x] i read somewhere that multiprocessing gives the flag "--multiprocessing-fork", might as well read for that too in sysgarv instead of just doing if name is main BECAUSE ITS ALL MAIN FOR SOME REASON IN PYINSTALLER
		- [x] have fcva return a hw button
		- [x] turn off everything and do a basic run of fcva in pyinstaller in ads.py
		- [x] maybe go to old pyinstaller ver?
		- [x] WHAT IS REALLY HAPPENING????
- [x] if kivy.deps does not work delete it
- [x] inspector not working... why?
- [x] most likely u just have to package libvlc.dll with pyinstaller then point to it properly
- [x] module import libvlc i think
- [x] THIS GUY HAS A SOLUTION
- [x] https://stackoverflow.com/a/48529272
- [x] just add libvlc.dll to specfile
- [x]  a.binaries + [("libVLC.dll", "C:/Program Files/VideoLAN/VLC/libvlc.dll", "BINARY")],
- [x] https://stackoverflow.com/questions/60247035/pyinstaller-with-python-vlc-no-attribute-media-player-new-error
- [x] One common answer to this problem is to make sure you have the VLC main programme installed, as the vlc.py relies on it. And also, that Python and the libvlc.dll both have to be 32-bit, or, both have to be 64-bit.
- [x] https://stackoverflow.com/questions/19546493/how-can-i-make-pyinstallers-spec-files-actually-portable-woes-absolute-path
- [x] write on kivyschool website I guess? idk
- [x] tell ppl to install vlc x64 I think? idk
- [x] https://github.com/pyinstaller/pyinstaller/issues/3448
- [x] maybe just include libvlc dll?
- [x] https://stackoverflow.com/a/48348399
- [x] more searches:
- [x] https://stackoverflow.com/questions/48683433/freezing-python-vlc-with-pyinstaller
- [x] https://stackoverflow.com/questions/74966894/making-an-executable-with-pyinstall-trouble-with-vlc-module-linux
- [x] https://stackoverflow.com/questions/71153531/exe-made-with-pyinstaller-cant-load-libvlc-dll-python-vlc
- [x] finished dec 2 2023
- [x] Copy current fcva dir and zip it (outside of venv so it's saved in git)
- [x] get BASE FCVA and BASE EXAMPLE > make pyinstaller version
- [x] updated font dp sizes
- [x] at least confirm it works (make a new folder to test it, nah just did naked install > pyinstaller after i saved latest fcva folder)
- [x] old ver of pyinstaller: "^5.13.2"
- [x] add vlc later tag: 
	- [x] #ADDVLC
- [x] creativecommonsmedia/elephants dream > bin/good night kiss
- [x] also giving it a kvstring is giga bad/breaking it (at least with base fcva)
- [x] stop checking for multiprocessing-fork
- [x] open_mediapipe_helper IS NOT IN A TRY EXCEPT BLOCK : - )
	- [x] for some reason the bin sourcelocation is bad/not searched through
		- [x] aka datas file HAS EVERYTHING just give what is needed
	- [x] this is incorrect?
		- [x] (basedir + "examples\\bin\\", "bin"),
		- [x] (going from examples bin to bin? isn't that bad?)
	- [x] didn't work, u gotta go slow...
		- [x] OR creativecommonsmedia has to be renamed back from bin
