### ISSUE TITLE
set icon > ICON IS BLURRY

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/213d#370]
- [ ] stupid answer:
- [ ] have it build right with correct icon then manually rename it
- [ ] do it correctly, sent it to #390
- [ ] MAKE A NEW ISSUE FOR THIS (fix icon not being set correctly by pyinstaller with name "amazing dance star", but "amazingdance star works") #390
- [x] rebuild icon cache?
- [x] https://www.wikihow.com/Rebuild-the-Icon-Cache-in-Windows
- [x] THERE IS LITERALLY NO CHANGE IN SPECFILE EXCEPT FOR NAME, ICON IS STILL WREKT, TRY DELETING BUILD FOLDE OR SMTH 
- [x] supply icon to fcva > need to do resources folder 1st tho
- [x] again, fix the redundant code... (sent to #382)
- [x] BLURRY AF
- [x] icotool?
- [x] https://github.com/qutebrowser/qutebrowser/issues/3601#issuecomment-365910097
- [x] check if pyinstaller build icon is blurry or not
- [x] using png works but is small, can fix later
