### ISSUE TITLE
(NOTES: HOW TO BUILD)pyinstaller checklist > creating exe

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/213d#397]
- [ ] **_GET A NEW ENV_** so compiled exe/.app is smaller, on windows u can have upx = True
- [ ] poetry shell
- [ ] `python -m PyInstaller specfile.spec --clean`
- [ ] hint/notes: debug on win/mac
- [ ] win: use cmd, `"amazing dance star.exe"`
- [ ] mac: use terminal, run `"/Users/raidraptorultimatefalcon/CODING/VDSpythonpivot/VDSpoetry2023/AmazingDanceStar/dist/Amazing Dance Star.app/Contents/MacOS/Amazing Dance Star" ; exit;` 
- [ ] THE `; exit;` IS NON-NEGOTIABLE
- [ ] do I need to make a .dmg? (probably yea) reference #398 
- [ ] dmg reference: https://medium.com/@jackhuang.wz/in-just-two-steps-you-can-turn-a-python-script-into-a-macos-application-installer-6e21bce2ee71
- [ ] after u run with cmd/terminal, search for "died", "error"
